# Generated by Django 2.1.1 on 2018-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Тело')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('chek', models.IntegerField(default=0, verbose_name='счетчик')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
    ]
